//! `lint`/`fmt`/`couplings`共通の設定ファイル（TOML）。
//!
//! ## 配置場所・探索順
//! - `--config <path>` が明示された場合はそのパスのみを読む（存在しなければエラー）。
//! - 明示が無い場合、カレントディレクトリ直下の `dat_linter.toml` を自動探索する。
//!   存在すればそれを読む。存在しなければ[`LintConfig::load_or_default`]は
//!   **何も書き込まず**、「設定ファイル無し」相当のデフォルト設定
//!   （全ルール有効・`language=en`）をそのまま返す。
//!
//! ## 設定ファイルの生成は`dat_linter init`のみが行う
//! かつては`load_or_default`がファイル未検出時にカレントディレクトリへ
//! コメント付きのデフォルト設定ファイルを自動生成していたが、この暗黙の副作用が
//! 意図しないディレクトリへの`dat_linter.toml`誤生成・テスト汚染の原因になったため
//! 廃止した（ユーザー確認済みの決定事項）。設定ファイルの生成は明示的な
//! `dat_linter init`サブコマンド（`src/commands/init.rs`）に一本化されている。
//! テンプレート文字列の生成ロジック（[`generate_default_config_file`]）自体は
//! ここに残し、`init`から`pub`関数として再利用する。
//!
//! ## スキーマ
//! ```toml
//! [general]
//! language = "en"  # "en" (デフォルト) または "ja"
//!
//! [rules]
//! include = ["obsolete-type", "missing-waytype"]
//! exclude = ["duplicate-key"]
//!
//! [tile_size]
//! default = 128
//! overrides = [
//!     { glob = "**/misc_GUI_64/**", size = 64 },
//! ]
//! ```
//!
//! ## `tile_size`（画像タイルサイズ、pak64/pak192等マルチサイズ対応）
//! `check_image_ref`（`rules/common.rs`）が画像サイズ・タイル座標の検証に使う
//! タイルサイズ（`makeobj pak<N>`のN）を解決する設定。次の優先順位で決まる
//! （高い方が勝つ。詳細な設計根拠は`rules/common.rs`の`DEFAULT_TILE_SIZE`
//! docコメント参照）:
//!
//! 1. `--tile-size` CLI引数（1回の実行に限る明示的な上書き）
//! 2. `.dat`ファイル自身の`cell_size=`フィールド（`obj_writer.cc:50`の
//!    `obj.get_int("cell_size", default_image_size)`に対応する実在のフィールド。
//!    ファイル単位の指定であり最も信頼できる情報源だが、実データでの使用例は
//!    稀）
//! 3. `[tile_size] overrides`: 検証対象パスに対する`glob`パターンマッチ
//!    （最初にマッチした要素を採用）。実際の`pak128/Makefile`が`DIRS64`/
//!    `DIRS128`でディレクトリ単位にビルド対象を振り分けている実例を模倣した、
//!    「1プロジェクト内でサイズが混在する」ケース向けの仕組み
//! 4. `[tile_size] default`（省略時は128）
//!
//! ## include/exclude の意味論
//! 1. `include` が空なら「全ルール（`Diagnostic.code`）が候補」。非空なら
//!    「`include` に列挙された code のみが候補」（それ以外の code は無条件で無効）。
//! 2. 上記の候補集合から、`exclude` に列挙された code をさらに除外する。
//!
//! つまり `exclude` は常に `include` より優先される（同じ code が両方に
//! 書かれていれば無効）。フィルタは`Diagnostic.code`単位の後段フィルタとして
//! 実装しており（`is_enabled`）、`Rule` trait や各obj種別モジュールの構造には
//! 一切手を入れていない（このツールの各ルールは`Diagnostic { code, .. }`を
//! 生成するだけの副作用フリーな設計のため、後段フィルタが最も低リスク）。
//!
//! ## `language`のデフォルト
//! 設定ファイルが無い場合・`[general] language`未指定の場合のデフォルトは
//! **英語（`en`）**（ユーザー確認済みの決定事項。既存の日本語固定挙動から
//! 変更されている点に注意。第1弾実装時点ではメッセージが日本語固定だったが、
//! i18n対応後はこのデフォルトに従う）。
//!
//! ## `fmt`のreorder挙動
//! `fmt`は慣習的な並び順に並び替えるのがデフォルト挙動（第5弾以降）。
//! 第11弾で専用の`[fmt] reorder`設定セクションを廃止し、既存の
//! `[rules] include/exclude`（`Diagnostic.code`単位）の仕組みに統合した:
//! reorder自体は`DiagnosticCode::FmtReorderApplied`（TOML上の文字列表現は
//! `"fmt-reorder-applied"`）というcode（機能トグル専用。実際にDiagnosticとして
//! 発行されることは無い）で表現され、`[rules] exclude`にこのcodeを追加すると
//! 恒久的にreorderを無効化できる
//! （`config.is_enabled(DiagnosticCode::FmtReorderApplied)`が`false`を返すようになる）。
//! CLIの`--no-reorder`フラグは、その1回の実行に限りconfig設定に関わらず
//! 強制的に無効化する（優先順位: `--no-reorder`指定 >
//! config（`[rules] exclude`にfmt-reorder-appliedがあれば無効、無ければ有効
//! ＝デフォルトtrue相当）)。専用の真偽値フィールドを持たないため、
//! 「デフォルトで有効」という事実上の初期値は`LintConfig::is_enabled`の
//! 「excludeに無ければ有効」という一般規則がそのまま担う。

use crate::i18n::{Language, t};
use serde::Deserialize;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

/// 自動探索時に見る・`dat_linter init`が書くファイル名。
pub const DEFAULT_CONFIG_FILENAME: &str = "dat_linter.toml";

/// `dat_linter init`がカレントディレクトリへ書き込むデフォルト内容。
/// コメントでスキーマの意味を説明し、値は全てデフォルト相当
/// （`language = "en"`・include/exclude空）にする。
const DEFAULT_CONFIG_TEMPLATE: &str = r#"# dat_linter configuration file
# Generated by `dat_linter init`. Feel free to edit or delete this file.
#
# [general]
# language: message language for lint/fmt/analyze output.
#   "en" (default) or "ja".
# language = "en"
#
# [rules]
# include: rule codes (Diagnostic.code) to enable. Empty = all rules enabled (default).
# exclude: rule codes to disable, applied after include. exclude always wins.
# include = []
# exclude = []
#
# Note: `fmt`'s key reordering is enabled by default and is controlled via this
# same include/exclude mechanism using the "fmt-reorder-applied" code. To
# permanently disable reordering, add it to exclude below:
#   exclude = ["fmt-reorder-applied"]
# (the CLI flag --no-reorder disables it for a single invocation instead).

[general]
language = "en"

[rules]
include = []
exclude = []

# [tile_size]
# default: image tile size (makeobj's pak<N>) used when nothing else applies.
#   Defaults to 128 (pak128) if omitted entirely.
# overrides: per-path glob -> tile size, checked in order (first match wins).
#   Mirrors how a real pak128/Makefile assigns some directories to DIRS64
#   instead of DIRS128 (e.g. a pak64-only GUI asset directory living inside
#   an otherwise pak128 tree).
# default = 128
# overrides = [
#     { glob = "**/misc_GUI_64/**", size = 64 },
# ]
"#;

#[derive(Debug, Default, Deserialize)]
struct RawConfig {
    #[serde(default)]
    general: RawGeneralConfig,
    #[serde(default)]
    rules: RawRulesConfig,
    #[serde(default)]
    tile_size: RawTileSizeConfig,
}

#[derive(Debug, Default, Deserialize)]
struct RawGeneralConfig {
    #[serde(default)]
    language: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
struct RawRulesConfig {
    #[serde(default)]
    include: Vec<String>,
    #[serde(default)]
    exclude: Vec<String>,
}

#[derive(Debug, Default, Deserialize)]
struct RawTileSizeConfig {
    #[serde(default)]
    default: Option<u32>,
    #[serde(default)]
    overrides: Vec<RawTileSizeOverride>,
}

#[derive(Debug, Deserialize)]
struct RawTileSizeOverride {
    glob: String,
    size: u32,
}

/// 読み込み・正規化済みの設定。`is_enabled`で`Diagnostic.code`ごとに
/// 有効/無効を判定し、`language()`で出力言語を取得する。
///
/// `fmt`のreorder挙動も`is_enabled(DiagnosticCode::FmtReorderApplied)`で判定する
/// （第11弾で専用の`fmt_reorder`フィールド・`[fmt] reorder`設定を廃止し、
/// 既存の`[rules] include/exclude`の仕組みに統合した。モジュール冒頭の
/// docコメント「`fmt`のreorder挙動」参照）。
#[derive(Debug)]
pub struct LintConfig {
    include: HashSet<String>,
    exclude: HashSet<String>,
    language: Language,
    tile_size_default: u32,
    /// パスへの`glob`マッチで解決するタイルサイズ上書き。宣言順を保持し、
    /// `tile_size_for`は最初にマッチした要素を採用する
    /// （TOML配列の順序＝ユーザーが書いた優先順位、という素直な解釈）。
    tile_size_overrides: Vec<(glob::Pattern, u32)>,
}

impl Default for LintConfig {
    fn default() -> Self {
        LintConfig::all_enabled()
    }
}

impl LintConfig {
    /// 全ルールが有効・言語はデフォルト(English)・タイルサイズは
    /// `DEFAULT_TILE_SIZE`(128)固定の設定（設定ファイル無しの状態と同義。
    /// fmtのreorderも`is_enabled(DiagnosticCode::FmtReorderApplied)`が
    /// `true`を返すため既定で有効）。
    pub fn all_enabled() -> Self {
        LintConfig {
            include: HashSet::new(),
            exclude: HashSet::new(),
            language: Language::default(),
            tile_size_default: crate::rules::common::DEFAULT_TILE_SIZE,
            tile_size_overrides: Vec::new(),
        }
    }

    /// `--config`指定または自動探索の結果に応じて設定を読み込む。
    ///
    /// - `explicit_path`が`Some`: そのパスを読む。存在しない・パースエラーは`Err`。
    /// - `explicit_path`が`None`: カレントディレクトリの`dat_linter.toml`を探す。
    ///   存在すればそれを読む。存在しなければ**何も書き込まず**
    ///   `Ok(LintConfig::all_enabled())`を返す（設定ファイル無し相当のデフォルト設定。
    ///   ファイル生成は`dat_linter init`サブコマンドでのみ行う。モジュール冒頭の
    ///   docコメント「設定ファイルの生成は`dat_linter init`のみが行う」参照）。
    pub fn load_or_default(explicit_path: Option<&Path>) -> Result<Self, String> {
        match explicit_path {
            Some(path) => Self::load_from(path),
            None => {
                let default_path = PathBuf::from(DEFAULT_CONFIG_FILENAME);
                if default_path.is_file() {
                    Self::load_from(&default_path)
                } else {
                    Ok(Self::all_enabled())
                }
            }
        }
    }

    /// 設定ファイル自体の読み込み・パースに失敗した場合のエラーメッセージ言語について:
    /// この時点では設定ファイルの中身（`[general] language`）がまだ読めていない
    /// （読めていれば、そもそもこの関数は成功して`Ok`を返している）ため、
    /// 「どの言語でエラーを報告すべきか」を設定ファイルから決めることができない
    /// （ニワトリが先か卵が先かの問題）。`--config`引数で明示的に指定した言語も
    /// 存在しない（`Language`はCLI引数ではなく設定ファイル経由でのみ選択される設計）。
    /// そのため、ここでのエラーメッセージは`Language::default()`（English）固定とする。
    /// 実用上も、設定ファイルが読めない/壊れているという状況を報告するメッセージが
    /// 意図した言語（`ja`）で出ないケースよりも、常に一貫した言語（English）で
    /// 出る方が挙動を予測しやすいと判断した。
    fn load_from(path: &Path) -> Result<Self, String> {
        let error_lang = Language::default();
        let text = std::fs::read_to_string(path).map_err(|e| {
            t!(error_lang,
                ja: "{p} を読み込めません ({e})",
                en: "Cannot read {p} ({e})",
                p = path.display(),
                e = e,
            )
        })?;
        let raw: RawConfig = toml::from_str(&text).map_err(|e| {
            t!(error_lang,
                ja: "{p} のTOML解析に失敗しました ({e})",
                en: "Failed to parse TOML in {p} ({e})",
                p = path.display(),
                e = e,
            )
        })?;
        let language = raw
            .general
            .language
            .as_deref()
            .and_then(Language::from_str)
            .unwrap_or_default();
        let tile_size_default = raw
            .tile_size
            .default
            .unwrap_or(crate::rules::common::DEFAULT_TILE_SIZE);
        let mut tile_size_overrides = Vec::with_capacity(raw.tile_size.overrides.len());
        for o in raw.tile_size.overrides {
            let pattern = glob::Pattern::new(&o.glob).map_err(|e| {
                t!(error_lang,
                    ja: "{p} の [tile_size] overrides に不正なglobパターンがあります (\"{glob}\": {e})",
                    en: "{p} has an invalid glob pattern in [tile_size] overrides (\"{glob}\": {e})",
                    p = path.display(),
                    glob = o.glob,
                    e = e,
                )
            })?;
            tile_size_overrides.push((pattern, o.size));
        }
        Ok(LintConfig {
            include: raw.rules.include.into_iter().collect(),
            exclude: raw.rules.exclude.into_iter().collect(),
            language,
            tile_size_default,
            tile_size_overrides,
        })
    }

    /// この`code`の診断を出力すべきか。
    /// `include`が空なら常に候補入り、非空なら`include`に含まれる場合のみ候補入り。
    /// その後`exclude`に含まれていればどちらの場合も無効化する。
    ///
    /// 第17弾: 引数を`&str`から`codes::DiagnosticCode`（enum）に変更した。
    /// TOMLの`[rules] include/exclude`自体は引き続きユーザーが手で書く文字列の
    /// リストのため、内部の`include`/`exclude`（`HashSet<String>`）は変更せず、
    /// `code.as_str()`で文字列化してから既存の判定ロジックにそのまま渡す。
    pub fn is_enabled(&self, code: crate::codes::DiagnosticCode) -> bool {
        let code = code.as_str();
        let included = self.include.is_empty() || self.include.contains(code);
        included && !self.exclude.contains(code)
    }

    /// 出力言語。設定ファイル無し・`[general] language`未指定の場合は
    /// `Language::default()`（English）。
    pub fn language(&self) -> Language {
        self.language
    }

    /// `path`（検証対象の`.dat`ファイルパス）に適用すべき画像タイルサイズを解決する。
    /// `[tile_size] overrides`を宣言順に見て最初にマッチした`glob`の`size`を返し、
    /// 何もマッチしなければ`[tile_size] default`（省略時`DEFAULT_TILE_SIZE`=128）を返す。
    ///
    /// `.dat`自身の`cell_size=`フィールドや`--tile-size`CLI引数はここでは扱わない
    /// （呼び出し元の`commands/lint.rs::lint_one_file_counts`が、この関数の戻り値を
    /// 含む優先順位付けをレコードごとに行う。モジュール冒頭docコメント
    /// 「`tile_size`（画像タイルサイズ）」参照）。
    pub fn tile_size_for(&self, path: &Path) -> u32 {
        for (pattern, size) in &self.tile_size_overrides {
            if pattern.matches_path(path) {
                return *size;
            }
        }
        self.tile_size_default
    }
}

/// `path`（通常はカレントディレクトリの`dat_linter.toml`）にコメント付きの
/// デフォルト設定ファイルを新規作成する。既にファイルが存在する場合は
/// 上書きせず`io::ErrorKind::AlreadyExists`の`Err`を返す（`create_new`で
/// アトミックに存在チェックと書き込みを行うため、TOCTOUによる意図しない
/// 上書きも起きない）。
///
/// `dat_linter init`サブコマンド（`src/commands/init.rs`、バイナリクレート側）
/// から呼ばれるため`pub`。`load_or_default`はもうこの関数を呼ばない
/// （モジュール冒頭のdocコメント「設定ファイルの生成は`dat_linter init`のみが
/// 行う」参照）。
pub fn generate_default_config_file(path: &Path) -> std::io::Result<()> {
    use std::io::Write;
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)?;
    file.write_all(DEFAULT_CONFIG_TEMPLATE.as_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codes::DiagnosticCode;

    #[test]
    fn all_enabled_allows_everything() {
        let cfg = LintConfig::all_enabled();
        assert!(cfg.is_enabled(DiagnosticCode::ObsoleteType));
        assert!(cfg.is_enabled(DiagnosticCode::DuplicateKey));
    }

    #[test]
    fn all_enabled_defaults_to_english() {
        assert_eq!(LintConfig::all_enabled().language(), Language::English);
    }

    #[test]
    fn empty_include_means_all_enabled_by_default() {
        let raw = RawConfig::default();
        let cfg = LintConfig {
            include: raw.rules.include.into_iter().collect(),
            exclude: raw.rules.exclude.into_iter().collect(),
            language: Language::default(),
            tile_size_default: crate::rules::common::DEFAULT_TILE_SIZE,
            tile_size_overrides: Vec::new(),
        };
        assert!(cfg.is_enabled(DiagnosticCode::ObsoleteType));
    }

    #[test]
    fn non_empty_include_restricts_to_listed_codes() {
        let cfg = LintConfig {
            include: ["obsolete-type".to_string()].into_iter().collect(),
            exclude: HashSet::new(),
            language: Language::default(),
            tile_size_default: crate::rules::common::DEFAULT_TILE_SIZE,
            tile_size_overrides: Vec::new(),
        };
        assert!(cfg.is_enabled(DiagnosticCode::ObsoleteType));
        assert!(!cfg.is_enabled(DiagnosticCode::MissingWaytype));
    }

    #[test]
    fn exclude_wins_even_if_also_included() {
        let cfg = LintConfig {
            include: ["obsolete-type".to_string()].into_iter().collect(),
            exclude: ["obsolete-type".to_string()].into_iter().collect(),
            language: Language::default(),
            tile_size_default: crate::rules::common::DEFAULT_TILE_SIZE,
            tile_size_overrides: Vec::new(),
        };
        assert!(!cfg.is_enabled(DiagnosticCode::ObsoleteType));
    }

    #[test]
    fn exclude_only_removes_from_default_all_enabled_set() {
        let cfg = LintConfig {
            include: HashSet::new(),
            exclude: ["duplicate-key".to_string()].into_iter().collect(),
            language: Language::default(),
            tile_size_default: crate::rules::common::DEFAULT_TILE_SIZE,
            tile_size_overrides: Vec::new(),
        };
        assert!(!cfg.is_enabled(DiagnosticCode::DuplicateKey));
        assert!(cfg.is_enabled(DiagnosticCode::ObsoleteType));
    }

    #[test]
    fn parses_toml_text() {
        let raw: RawConfig = toml::from_str(
            r#"
            [rules]
            include = ["obsolete-type", "missing-waytype"]
            exclude = ["missing-waytype"]
            "#,
        )
        .unwrap();
        let cfg = LintConfig {
            include: raw.rules.include.into_iter().collect(),
            exclude: raw.rules.exclude.into_iter().collect(),
            language: Language::default(),
            tile_size_default: crate::rules::common::DEFAULT_TILE_SIZE,
            tile_size_overrides: Vec::new(),
        };
        assert!(cfg.is_enabled(DiagnosticCode::ObsoleteType));
        assert!(!cfg.is_enabled(DiagnosticCode::MissingWaytype));
        assert!(!cfg.is_enabled(DiagnosticCode::DuplicateKey));
    }

    #[test]
    fn parses_language_ja() {
        let raw: RawConfig = toml::from_str(
            r#"
            [general]
            language = "ja"
            "#,
        )
        .unwrap();
        assert_eq!(raw.general.language.as_deref(), Some("ja"));
    }

    #[test]
    fn missing_language_key_defaults_to_english_via_load_from() {
        let tmp = std::env::temp_dir().join("dat_linter_test_no_language_key.toml");
        std::fs::write(&tmp, "[rules]\ninclude = []\n").unwrap();
        let cfg = LintConfig::load_from(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert_eq!(cfg.language(), Language::English);
    }

    #[test]
    fn explicit_ja_language_is_honored_via_load_from() {
        let tmp = std::env::temp_dir().join("dat_linter_test_ja_language.toml");
        std::fs::write(&tmp, "[general]\nlanguage = \"ja\"\n").unwrap();
        let cfg = LintConfig::load_from(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert_eq!(cfg.language(), Language::Japanese);
    }

    #[test]
    fn unknown_language_value_falls_back_to_english() {
        let tmp = std::env::temp_dir().join("dat_linter_test_unknown_language.toml");
        std::fs::write(&tmp, "[general]\nlanguage = \"fr\"\n").unwrap();
        let cfg = LintConfig::load_from(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert_eq!(cfg.language(), Language::English);
    }

    /// 第11弾: `fmt`のreorderは専用設定ではなく`[rules] exclude`に
    /// `"fmt-reorder-applied"`を書くことで無効化する方式に変わった。
    /// `LintConfig`自体はこのcode名を特別扱いしないため（`is_enabled`は
    /// あらゆるcode文字列に対して同じ意味論で動く）、ここでは
    /// 「excludeに書けば無効、書かなければ有効（デフォルトtrue相当）」という
    /// 一般的なinclude/exclude意味論がfmt-reorder-appliedにもそのまま
    /// 適用されることを固定する。
    #[test]
    fn all_enabled_treats_fmt_reorder_applied_as_enabled_by_default() {
        assert!(LintConfig::all_enabled().is_enabled(DiagnosticCode::FmtReorderApplied));
    }

    #[test]
    fn excluding_fmt_reorder_applied_disables_it_via_load_from() {
        let tmp = std::env::temp_dir().join("dat_linter_test_exclude_fmt_reorder_applied.toml");
        std::fs::write(&tmp, "[rules]\nexclude = [\"fmt-reorder-applied\"]\n").unwrap();
        let cfg = LintConfig::load_from(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert!(!cfg.is_enabled(DiagnosticCode::FmtReorderApplied));
    }

    #[test]
    fn generate_default_config_file_has_no_fmt_section() {
        let tmp = std::env::temp_dir().join("dat_linter_test_generated_config_no_fmt.toml");
        let _ = std::fs::remove_file(&tmp);
        generate_default_config_file(&tmp).expect("生成に失敗");
        let content = std::fs::read_to_string(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert!(
            !content.contains("[fmt]"),
            "[fmt] セクションは廃止されたため生成内容に含まれないべき: {content}"
        );
        assert!(
            content.contains("fmt-reorder-applied"),
            "fmt-reorder-appliedによる無効化方法の案内コメントが含まれるべき: {content}"
        );
        // 生成された内容自体が正しくパースできることも確認する（[fmt]セクション無しで
        // RawConfigがデフォルト値にフォールバックすること）。
        let raw: RawConfig = toml::from_str(&content).expect("生成された設定のパースに失敗");
        assert_eq!(raw.general.language.as_deref(), Some("en"));
    }

    /// 設定ファイル自体が存在しない場合の読み込みエラーメッセージは、
    /// `load_from`のdocコメントに記載の通り常に`Language::default()`（English）
    /// 固定である（設定ファイルの中身が読めていない時点でユーザーの言語選択を
    /// 知りようがないため）。この方針が実際にコード側でも守られていることを固定する。
    #[test]
    fn unreadable_file_error_message_is_always_english() {
        let tmp = std::env::temp_dir().join("dat_linter_test_nonexistent_file_for_error.toml");
        let _ = std::fs::remove_file(&tmp);
        let err = LintConfig::load_from(&tmp).unwrap_err();
        assert!(
            err.contains("Cannot read"),
            "存在しないファイルのエラーは常に英語であるべき: {err:?}"
        );
        assert!(
            !err.contains("読み込めません"),
            "存在しないファイルのエラーに日本語文字列が混入している: {err:?}"
        );
    }

    /// 不正なTOML構文のパースエラーメッセージも同様に常にEnglish固定。
    #[test]
    fn invalid_toml_error_message_is_always_english() {
        let tmp = std::env::temp_dir().join("dat_linter_test_invalid_toml.toml");
        std::fs::write(&tmp, "this is not valid toml [[[").unwrap();
        let err = LintConfig::load_from(&tmp).unwrap_err();
        let _ = std::fs::remove_file(&tmp);
        assert!(
            err.contains("Failed to parse TOML"),
            "不正なTOMLのエラーは常に英語であるべき: {err:?}"
        );
        assert!(
            !err.contains("TOML解析に失敗しました"),
            "不正なTOMLのエラーに日本語文字列が混入している: {err:?}"
        );
    }

    #[test]
    fn generate_default_config_file_writes_template_with_general_and_rules_sections() {
        let tmp = std::env::temp_dir().join("dat_linter_test_generated_config.toml");
        let _ = std::fs::remove_file(&tmp);
        generate_default_config_file(&tmp).expect("生成に失敗");
        let content = std::fs::read_to_string(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert!(content.contains("[general]"));
        assert!(content.contains("language"));
        assert!(content.contains("[rules]"));
        // 生成された内容自体が正しくパースできることも確認する。
        let raw: RawConfig = toml::from_str(&content).expect("生成された設定のパースに失敗");
        assert_eq!(raw.general.language.as_deref(), Some("en"));
    }

    #[test]
    fn generate_default_config_file_does_not_overwrite_existing_file() {
        let tmp = std::env::temp_dir().join("dat_linter_test_existing_config.toml");
        std::fs::write(&tmp, "# custom content\n[rules]\ninclude=[\"x\"]\n").unwrap();
        let result = generate_default_config_file(&tmp);
        let content_after = std::fs::read_to_string(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert!(result.is_err(), "既存ファイルへの上書きはエラーになるべき");
        assert!(content_after.contains("custom content"));
    }

    #[test]
    fn all_enabled_tile_size_defaults_to_128() {
        let cfg = LintConfig::all_enabled();
        assert_eq!(cfg.tile_size_for(Path::new("anything.dat")), 128);
    }

    #[test]
    fn tile_size_default_is_honored_via_load_from() {
        let tmp = std::env::temp_dir().join("dat_linter_test_tile_size_default.toml");
        std::fs::write(&tmp, "[tile_size]\ndefault = 64\n").unwrap();
        let cfg = LintConfig::load_from(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert_eq!(cfg.tile_size_for(Path::new("anywhere/foo.dat")), 64);
    }

    #[test]
    fn tile_size_override_wins_for_matching_path() {
        let tmp = std::env::temp_dir().join("dat_linter_test_tile_size_override.toml");
        std::fs::write(
            &tmp,
            "[tile_size]\ndefault = 128\noverrides = [{ glob = \"**/misc_GUI_64/**\", size = 64 }]\n",
        )
        .unwrap();
        let cfg = LintConfig::load_from(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert_eq!(
            cfg.tile_size_for(Path::new("base/misc_GUI_64/wkz_icons.dat")),
            64
        );
        assert_eq!(cfg.tile_size_for(Path::new("base/misc_GUI/mouse.dat")), 128);
    }

    #[test]
    fn first_matching_tile_size_override_wins() {
        let tmp = std::env::temp_dir().join("dat_linter_test_tile_size_override_order.toml");
        std::fs::write(
            &tmp,
            "[tile_size]\n\
             default = 128\n\
             overrides = [\n\
             { glob = \"**/gui/**\", size = 64 },\n\
             { glob = \"**/gui/big/**\", size = 192 },\n\
             ]\n",
        )
        .unwrap();
        let cfg = LintConfig::load_from(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        // "gui/big/"配下も先に書かれた"gui/**"に先勝ちでマッチする（宣言順優先）。
        assert_eq!(cfg.tile_size_for(Path::new("gui/big/logo.dat")), 64);
    }

    #[test]
    fn invalid_tile_size_override_glob_is_rejected() {
        let tmp = std::env::temp_dir().join("dat_linter_test_tile_size_invalid_glob.toml");
        std::fs::write(
            &tmp,
            "[tile_size]\noverrides = [{ glob = \"[\", size = 64 }]\n",
        )
        .unwrap();
        let err = LintConfig::load_from(&tmp).unwrap_err();
        let _ = std::fs::remove_file(&tmp);
        assert!(
            err.contains("tile_size"),
            "不正なglobパターンのエラーメッセージに[tile_size]の文脈が含まれるべき: {err:?}"
        );
    }
}
